"""Discord 适配器共享常量。"""

DISCORD_GATEWAY_NAME = "discord_gateway"
DISCORD_PLATFORM = "discord"
DISCORD_PROTOCOL = "discord"

SUPPORTED_CONFIG_VERSION = "1.0.0-alpha"

DEFAULT_PLATFORM_NAME = "discord"
DEFAULT_RETRY_DELAY_SEC = 5
DEFAULT_CONNECTION_CHECK_INTERVAL_SEC = 30
DEFAULT_HEALTH_CHECK_INTERVAL_SEC = 60
DEFAULT_HEALTH_CHECK_MAX_FAILURES = 3
DEFAULT_TTS_PLAYBACK_LEADING_SILENCE_MS = 1000

DEFAULT_CHAT_LIST_TYPE = "blacklist"
